### ISSUE TITLE
Assertion error with BlueMuse

### ISSUE THREAD

**Issue by dice10240** [operatorequals/muse-osc#1]
thank you very much for release this software.

It works with muselsl and it sends data to Neuromore studio via UDP4545 port.
I can see Alpha Beta 10Hz waves.

When I use BlueMuse instead of muselsl, python tells assertion error.
This is log, can you tell me how to fix?
—-

6abaf2e8be/branch:refs/tags/v1.16.2/build:Release/compiler:MSVC-19.0.24245.0/link:SHARED
Streams available: {'EEG': <pylsl.pylsl.StreamInlet object at 0x000001DBE0D0C7F0>, 'accelerometer': None, 'PPG': None, 'gyroscope': None}
Start streaming data for 3600 seconds
Exception in thread Thread-1 (_stream_handler):
Traceback (most recent call last):
  File "C:\Users\d2\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\d2\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\d2\Desktop\muse-osc-master\muse_osc\__main__.py", line 72, in _stream_handler
    assert len(sample) == 5 # TP9, AF7, AF8, TP10, AUX
AssertionError

**Comment by operatorequals** [comment]
Hey @dice10240 
I'm really glad it helped and works for you!

So, this assertion is there to ensure that the LSL brings all 5 electrode inputs
to the `muse-osc`. Here, it looks like it brings different inputs (misses the AUX?, I don't know).

I can't currently test BlueMuse, so if you are familiar with Python you can add a `print` statement,
figuring out what exactly does `sample` variable contains when `BlueMuse` handles the LSL
and post the output here.

Alternatively, I think [`MuseLSL2`](https://github.com/DominiqueMakowski/MuseLSL2) should work out of the box too (as it advertises direct compatibility with `muse-lsl`).

**Comment by operatorequals** [comment]
Also be sure to use the last version of `BlueMuse`.
They advertise adding support for `AUX` channel for Muse 2 in [`2.3.0.0`](https://github.com/kowalej/BlueMuse?tab=readme-ov-file#versions)

**Comment by dice10240** [comment]
I confirmed MuseLSL2 works with your code as well as MuseLSL.
Thank you

**Comment by operatorequals** [comment]
Hello @dice10240 !
Glad it worked!
Did you check the last version of BlueMuse?
If it works we can close the issue!
If it does not, let's keep it open, so we can eventually debug it and find out what's going on, so we make it work as well!
